package:
  name: flex
  version: "2.5.39"

source:
  url: http://iweb.dl.sourceforge.net/project/flex/flex-2.5.39.tar.bz2   
  fn: flex-2.5.39.tar.bz2

build:
  number: 1

requirements:
  build:
    - system
    - gcc
    - m4
    - autoconf
    - automake
    - pkg-config
    - libtool
  run:
    - system

about:
  home: http://sourceforge.net/projects/flex/ 
  license: BSD
  summary: "flex is a tool for generating scanners."
